# Generated by Django 5.1.5 on 2025-03-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=20)),
                ('precio_dolares', models.CharField(max_length=20)),
                ('fecha_compra', models.DateField(null=True)),
            ],
        ),
    ]
