# Generated by Django 5.1.5 on 2025-03-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='fechra_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
