# Generated by Django 5.1.5 on 2025-03-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
